export type BookingStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled'

export interface Booking {
  id: number
  customerName: string
  customerEmail: string
  customerPhone: string
  serviceName: string
  serviceCategory: string
  providerName: string
  location: string
  eventDate: string
  createdAt: string
  status: BookingStatus
  amount: number
  notes: string
}

export const ADMIN_BOOKINGS_SEED: Booking[] = [
  {
    id: 1,
    customerName: 'Sarah Nkurunziza',
    customerEmail: 'sarah.n@gmail.com',
    customerPhone: '+250 788 201 001',
    serviceName: 'Luxury Wedding Photography',
    serviceCategory: 'photography',
    providerName: 'Golden Lens Studio',
    location: 'Downtown',
    eventDate: 'Jun 14, 2026',
    createdAt: 'May 1, 2026',
    status: 'confirmed',
    amount: 5000,
    notes: 'Drone coverage included. Setup at 8 AM.',
  },
  {
    id: 2,
    customerName: 'James Mugisha',
    customerEmail: 'james.m@email.rw',
    customerPhone: '+250 788 201 002',
    serviceName: 'Premium Wedding Car Service',
    serviceCategory: 'vehicles',
    providerName: 'LuxRide Rwanda',
    location: 'Remera',
    eventDate: 'Jun 20, 2026',
    createdAt: 'May 3, 2026',
    status: 'confirmed',
    amount: 2500,
    notes: 'Two limousines required. Pick-up at Serena Hotel.',
  },
  {
    id: 3,
    customerName: 'Grace Uwimana',
    customerEmail: 'grace.u@yahoo.com',
    customerPhone: '+250 788 201 003',
    serviceName: 'Professional MC & Emcee Service',
    serviceCategory: 'mc',
    providerName: 'EventPro Rwanda',
    location: 'Kigali City',
    eventDate: 'Jul 5, 2026',
    createdAt: 'May 5, 2026',
    status: 'pending',
    amount: 3000,
    notes: 'Bilingual MC required (English & Kinyarwanda).',
  },
  {
    id: 4,
    customerName: 'Patrick Habimana',
    customerEmail: 'patrick.h@gmail.com',
    customerPhone: '+250 788 201 004',
    serviceName: 'Premium Sound & Lighting',
    serviceCategory: 'sound',
    providerName: 'SoundWave Pro',
    location: 'Nyamirambo',
    eventDate: 'May 25, 2026',
    createdAt: 'Apr 20, 2026',
    status: 'completed',
    amount: 4000,
    notes: 'Full stage setup with LED wall.',
  },
  {
    id: 5,
    customerName: 'Alice Mukamana',
    customerEmail: 'alice.mk@email.rw',
    customerPhone: '+250 788 201 005',
    serviceName: 'Professional Catering Service',
    serviceCategory: 'catering',
    providerName: 'Taste of Rwanda',
    location: 'Kimironko',
    eventDate: 'Jun 28, 2026',
    createdAt: 'May 6, 2026',
    status: 'pending',
    amount: 6000,
    notes: '200 guests. Mix of local and international menu.',
  },
  {
    id: 6,
    customerName: 'David Niyonzima',
    customerEmail: 'david.n@gmail.com',
    customerPhone: '+250 788 201 006',
    serviceName: 'Event Coordination Team',
    serviceCategory: 'mc',
    providerName: 'PlanIt Events',
    location: 'Downtown',
    eventDate: 'May 10, 2026',
    createdAt: 'Apr 10, 2026',
    status: 'completed',
    amount: 3500,
    notes: 'Full-day coordination for graduation ceremony.',
  },
  {
    id: 7,
    customerName: 'Marie Claire Ingabire',
    customerEmail: 'mc.ingabire@yahoo.com',
    customerPhone: '+250 788 201 007',
    serviceName: 'Luxury Wedding Photography',
    serviceCategory: 'photography',
    providerName: 'Golden Lens Studio',
    location: 'Downtown',
    eventDate: 'Aug 2, 2026',
    createdAt: 'May 8, 2026',
    status: 'confirmed',
    amount: 5000,
    notes: 'Extra album package requested.',
  },
  {
    id: 8,
    customerName: 'Eric Kamanzi',
    customerEmail: 'eric.k@gmail.com',
    customerPhone: '+250 788 201 008',
    serviceName: 'Premium Sound & Lighting',
    serviceCategory: 'sound',
    providerName: 'SoundWave Pro',
    location: 'Kimironko',
    eventDate: 'Apr 30, 2026',
    createdAt: 'Apr 5, 2026',
    status: 'cancelled',
    amount: 4000,
    notes: 'Cancelled due to venue change.',
  },
  {
    id: 9,
    customerName: 'Claudine Uwase',
    customerEmail: 'claudine.u@email.rw',
    customerPhone: '+250 788 201 009',
    serviceName: 'Professional Catering Service',
    serviceCategory: 'catering',
    providerName: 'Taste of Rwanda',
    location: 'Kigali City',
    eventDate: 'Jul 19, 2026',
    createdAt: 'May 9, 2026',
    status: 'pending',
    amount: 6000,
    notes: '300 guests. Traditional Rwandan menu preferred.',
  },
  {
    id: 10,
    customerName: 'Samuel Uwimana',
    customerEmail: 'samuel.u@gmail.com',
    customerPhone: '+250 788 201 010',
    serviceName: 'Premium Wedding Car Service',
    serviceCategory: 'vehicles',
    providerName: 'LuxRide Rwanda',
    location: 'Remera',
    eventDate: 'Sep 6, 2026',
    createdAt: 'May 10, 2026',
    status: 'confirmed',
    amount: 2500,
    notes: 'Classic rolls royce requested for bride.',
  },
]
