export type UserStatus = 'active' | 'suspended' | 'pending'
export type UserRole   = 'customer' | 'provider'

export interface AdminUser {
  id: number
  name: string
  email: string
  phone: string
  role: UserRole
  status: UserStatus
  location: string
  joinedAt: string
  bookings: number
  totalSpent: number
  lastActive: string
  bio: string
}

export const ADMIN_USERS_SEED: AdminUser[] = [
  {
    id: 1,
    name: 'Sarah Nkurunziza',
    email: 'sarah.n@gmail.com',
    phone: '+250 788 201 001',
    role: 'customer',
    status: 'active',
    location: 'Kigali City',
    joinedAt: 'Jan 5, 2024',
    bookings: 4,
    totalSpent: 16500,
    lastActive: 'May 9, 2026',
    bio: 'Event enthusiast who loves planning perfect ceremonies for family milestones.',
  },
  {
    id: 2,
    name: 'James Mugisha',
    email: 'james.m@email.rw',
    phone: '+250 788 201 002',
    role: 'customer',
    status: 'active',
    location: 'Remera',
    joinedAt: 'Feb 12, 2024',
    bookings: 2,
    totalSpent: 7500,
    lastActive: 'May 8, 2026',
    bio: 'Corporate event coordinator looking for reliable service vendors.',
  },
  {
    id: 3,
    name: 'Grace Uwimana',
    email: 'grace.u@yahoo.com',
    phone: '+250 788 201 003',
    role: 'customer',
    status: 'active',
    location: 'Downtown',
    joinedAt: 'Mar 1, 2024',
    bookings: 3,
    totalSpent: 12000,
    lastActive: 'May 7, 2026',
    bio: 'Wedding planner assistant who books services on behalf of clients.',
  },
  {
    id: 4,
    name: 'Patrick Habimana',
    email: 'patrick.h@gmail.com',
    phone: '+250 788 201 004',
    role: 'customer',
    status: 'active',
    location: 'Nyamirambo',
    joinedAt: 'Mar 20, 2024',
    bookings: 5,
    totalSpent: 22000,
    lastActive: 'May 5, 2026',
    bio: 'Passionate about hosting memorable events for family and friends.',
  },
  {
    id: 5,
    name: 'Alice Mukamana',
    email: 'alice.mk@email.rw',
    phone: '+250 788 201 005',
    role: 'provider',
    status: 'active',
    location: 'Kimironko',
    joinedAt: 'Apr 2, 2024',
    bookings: 18,
    totalSpent: 0,
    lastActive: 'May 10, 2026',
    bio: 'Professional caterer with 8 years of experience in high-end event catering.',
  },
  {
    id: 6,
    name: 'David Niyonzima',
    email: 'david.n@gmail.com',
    phone: '+250 788 201 006',
    role: 'customer',
    status: 'active',
    location: 'Downtown',
    joinedAt: 'Apr 10, 2024',
    bookings: 1,
    totalSpent: 3500,
    lastActive: 'May 3, 2026',
    bio: 'University professor organising annual graduation ceremonies.',
  },
  {
    id: 7,
    name: 'Marie Claire Ingabire',
    email: 'mc.ingabire@yahoo.com',
    phone: '+250 788 201 007',
    role: 'provider',
    status: 'active',
    location: 'Downtown',
    joinedAt: 'Apr 18, 2024',
    bookings: 12,
    totalSpent: 0,
    lastActive: 'May 9, 2026',
    bio: 'Award-winning MC and event host with 6 years of experience in bilingual ceremonies.',
  },
  {
    id: 8,
    name: 'Eric Kamanzi',
    email: 'eric.k@gmail.com',
    phone: '+250 788 201 008',
    role: 'customer',
    status: 'suspended',
    location: 'Kimironko',
    joinedAt: 'Apr 30, 2024',
    bookings: 2,
    totalSpent: 4000,
    lastActive: 'Apr 28, 2026',
    bio: 'Account suspended due to payment dispute.',
  },
  {
    id: 9,
    name: 'Claudine Uwase',
    email: 'claudine.u@email.rw',
    phone: '+250 788 201 009',
    role: 'customer',
    status: 'active',
    location: 'Kigali City',
    joinedAt: 'May 2, 2024',
    bookings: 3,
    totalSpent: 14000,
    lastActive: 'May 10, 2026',
    bio: 'Bride-to-be planning a dream wedding ceremony for August 2026.',
  },
  {
    id: 10,
    name: 'Samuel Uwimana',
    email: 'samuel.u@gmail.com',
    phone: '+250 788 201 010',
    role: 'customer',
    status: 'pending',
    location: 'Remera',
    joinedAt: 'May 10, 2024',
    bookings: 0,
    totalSpent: 0,
    lastActive: 'May 10, 2026',
    bio: 'New user. Account pending email verification.',
  },
  {
    id: 11,
    name: 'Jean Paul Mugisha',
    email: 'jp.mugisha@goldenlens.rw',
    phone: '+250 788 100 001',
    role: 'provider',
    status: 'active',
    location: 'Kigali City',
    joinedAt: 'Jan 10, 2024',
    bookings: 25,
    totalSpent: 0,
    lastActive: 'May 10, 2026',
    bio: 'Owner of Golden Lens Studio — Rwanda\'s top wedding photography studio.',
  },
  {
    id: 12,
    name: 'Alice Uwimana',
    email: 'bookings@luxride.rw',
    phone: '+250 788 100 002',
    role: 'provider',
    status: 'pending',
    location: 'Remera',
    joinedAt: 'May 8, 2024',
    bookings: 0,
    totalSpent: 0,
    lastActive: 'May 8, 2026',
    bio: 'New provider account for LuxRide Rwanda — awaiting admin verification.',
  },
]
