export type PaymentStatus = 'completed' | 'pending' | 'failed' | 'refunded'
export type PaymentMethod = 'momo' | 'card' | 'bank' | 'cash'

export interface Payment {
  id: number
  reference: string
  customerName: string
  customerEmail: string
  providerName: string
  serviceName: string
  serviceCategory: string
  amount: number
  platformFee: number
  providerPayout: number
  method: PaymentMethod
  status: PaymentStatus
  date: string
  bookingId: number
  notes: string
}

export const ADMIN_PAYMENTS_SEED: Payment[] = [
  {
    id: 1,
    reference: 'PAY-2026-0001',
    customerName: 'Sarah Nkurunziza',
    customerEmail: 'sarah.n@gmail.com',
    providerName: 'Golden Lens Studio',
    serviceName: 'Luxury Wedding Photography',
    serviceCategory: 'photography',
    amount: 5000,
    platformFee: 250,
    providerPayout: 4750,
    method: 'momo',
    status: 'completed',
    date: 'May 1, 2026',
    bookingId: 1,
    notes: 'Full payment received via MTN MoMo.',
  },
  {
    id: 2,
    reference: 'PAY-2026-0002',
    customerName: 'James Mugisha',
    customerEmail: 'james.m@email.rw',
    providerName: 'LuxRide Rwanda',
    serviceName: 'Premium Wedding Car Service',
    serviceCategory: 'vehicles',
    amount: 2500,
    platformFee: 125,
    providerPayout: 2375,
    method: 'card',
    status: 'completed',
    date: 'May 3, 2026',
    bookingId: 2,
    notes: 'Paid by Visa card. Deposit only.',
  },
  {
    id: 3,
    reference: 'PAY-2026-0003',
    customerName: 'Grace Uwimana',
    customerEmail: 'grace.u@yahoo.com',
    providerName: 'EventPro Rwanda',
    serviceName: 'Professional MC & Emcee Service',
    serviceCategory: 'mc',
    amount: 3000,
    platformFee: 150,
    providerPayout: 2850,
    method: 'momo',
    status: 'pending',
    date: 'May 5, 2026',
    bookingId: 3,
    notes: 'Awaiting payment confirmation from customer.',
  },
  {
    id: 4,
    reference: 'PAY-2026-0004',
    customerName: 'Patrick Habimana',
    customerEmail: 'patrick.h@gmail.com',
    providerName: 'SoundWave Pro',
    serviceName: 'Premium Sound & Lighting',
    serviceCategory: 'sound',
    amount: 4000,
    platformFee: 200,
    providerPayout: 3800,
    method: 'bank',
    status: 'completed',
    date: 'Apr 20, 2026',
    bookingId: 4,
    notes: 'Bank transfer confirmed. Event completed.',
  },
  {
    id: 5,
    reference: 'PAY-2026-0005',
    customerName: 'Alice Mukamana',
    customerEmail: 'alice.mk@email.rw',
    providerName: 'Taste of Rwanda',
    serviceName: 'Professional Catering Service',
    serviceCategory: 'catering',
    amount: 6000,
    platformFee: 300,
    providerPayout: 5700,
    method: 'momo',
    status: 'pending',
    date: 'May 6, 2026',
    bookingId: 5,
    notes: '50% deposit pending. Balance due on event day.',
  },
  {
    id: 6,
    reference: 'PAY-2026-0006',
    customerName: 'David Niyonzima',
    customerEmail: 'david.n@gmail.com',
    providerName: 'PlanIt Events',
    serviceName: 'Event Coordination Team',
    serviceCategory: 'mc',
    amount: 3500,
    platformFee: 175,
    providerPayout: 3325,
    method: 'cash',
    status: 'completed',
    date: 'Apr 10, 2026',
    bookingId: 6,
    notes: 'Cash payment collected at event.',
  },
  {
    id: 7,
    reference: 'PAY-2026-0007',
    customerName: 'Marie Claire Ingabire',
    customerEmail: 'mc.ingabire@yahoo.com',
    providerName: 'Golden Lens Studio',
    serviceName: 'Luxury Wedding Photography',
    serviceCategory: 'photography',
    amount: 5000,
    platformFee: 250,
    providerPayout: 4750,
    method: 'card',
    status: 'completed',
    date: 'May 8, 2026',
    bookingId: 7,
    notes: 'Full payment via MasterCard.',
  },
  {
    id: 8,
    reference: 'PAY-2026-0008',
    customerName: 'Eric Kamanzi',
    customerEmail: 'eric.k@gmail.com',
    providerName: 'SoundWave Pro',
    serviceName: 'Premium Sound & Lighting',
    serviceCategory: 'sound',
    amount: 4000,
    platformFee: 200,
    providerPayout: 3800,
    method: 'momo',
    status: 'refunded',
    date: 'Apr 5, 2026',
    bookingId: 8,
    notes: 'Refunded after booking cancellation.',
  },
  {
    id: 9,
    reference: 'PAY-2026-0009',
    customerName: 'Claudine Uwase',
    customerEmail: 'claudine.u@email.rw',
    providerName: 'Taste of Rwanda',
    serviceName: 'Professional Catering Service',
    serviceCategory: 'catering',
    amount: 6000,
    platformFee: 300,
    providerPayout: 5700,
    method: 'bank',
    status: 'pending',
    date: 'May 9, 2026',
    bookingId: 9,
    notes: 'Bank transfer initiated. Awaiting settlement.',
  },
  {
    id: 10,
    reference: 'PAY-2026-0010',
    customerName: 'Samuel Uwimana',
    customerEmail: 'samuel.u@gmail.com',
    providerName: 'LuxRide Rwanda',
    serviceName: 'Premium Wedding Car Service',
    serviceCategory: 'vehicles',
    amount: 2500,
    platformFee: 125,
    providerPayout: 2375,
    method: 'momo',
    status: 'failed',
    date: 'May 10, 2026',
    bookingId: 10,
    notes: 'MoMo transaction failed. Customer to retry.',
  },
]
